firmware/applications/SignBuddy/Makefile, firmware/applications/SignBuddy/board.h, firmware/applications/SignBuddy/main.c, firmware/libraries/system_time/system_time.c, firmware/libraries/system_time/system_time.h
add system time module for keeping system time lol - 
uses hardware timer on 1 us tick
=> add system time to app

firmware/firmware_style.cfg, firmware/run_formatter.sh
add uncrustify formatter config and format script
=> Add firmware C formatter

firmware/applications/SignBuddy/board.h, firmware/applications/SignBuddy/gpio.c, firmware/applications/SignBuddy/main.c, firmware/applications/SignBuddy/system_stm32l4xx.c, firmware/firmware_style.cfg, firmware/libraries/system_time/system_time.c, firmware/libraries/system_time/system_time.h, firmware/run_formatter.sh
run formatter script didn't work
ran the formatter on the codebase
=> Formatter fixes, and run on codebase

firmware/compile.sh
there was some issue on my machine with the `&>>`
=> Fix docker image build in compile.sh

firmware/tools/build_docker_image.sh, firmware/tools/compile.sh, firmware/tools/run_formatter.sh
move docker build logic and building to its own script
change variables to be `$VARIABLE` instead of `${VARIABLE}`
=> abstract docker image building to own script

firmware/tools/firmware_style.cfg
=> fix one line while issue Closes #18

firmware/applications/SignBuddy/adc.c, firmware/applications/SignBuddy/ble_uart.c, firmware/applications/SignBuddy/disco_board.h, firmware/applications/SignBuddy/main.c, firmware/applications/SignBuddy/nucleo_board.h
* Closes #20 
* Abstract LPUART from BLE UART module
* Removed priority encoding function for consistency with LOG UART
* Fixed ADC IRQ naming to match pattern
* Added to do for BLE UART on the discovery board
=> Fixed BLE UART data size, abstracted LPUART and formatting

.gitattributes, firmware/Makefile, firmware/tools/Dockerfile, firmware/tools/docker_run_formatter.sh, firmware/tools/formatter_blacklist.txt, firmware/tools/run_formatter.sh
- Separate into docker and non docker script
- Add blacklist file
=> Revamp formatter script

.gitmodules
I don't think there's any need for me to have a fork of this
=> Switch stm32l0 source to STM repo

firmware/applications/SignBuddy/Makefile, firmware/applications/SignBuddy/i2c.c, firmware/applications/SignBuddy/i2c.h, firmware/applications/SignBuddy/imu.c, firmware/applications/SignBuddy/imu.h, firmware/applications/SignBuddy/main.c, firmware/applications/SignBuddy/nucleo_board.h, firmware/libraries/bno055/bno055.c, firmware/libraries/bno055/bno055.h, firmware/libraries/bno055/bno055_support.c, firmware/tools/formatter_blacklist.txt
=> add imu module

firmware/applications/SignBuddy/FreeRTOSConfig.h, firmware/applications/SignBuddy/Makefile, firmware/applications/SignBuddy/common.h, firmware/applications/SignBuddy/main.c, firmware/applications/SignBuddy/sensors.c, firmware/applications/SignBuddy/sensors.h, firmware/applications/SignBuddy/task_config.h
I was looking at the architecture of the application and it's gotten too complex. hopefully we can reduce some of this complexity by using freertos.
though i am worried we will run low on memory
=> integrate freertos into app

firmware/applications/SignBuddy/i2c.c, firmware/applications/SignBuddy/i2c.h
=> Add error handling for I2C

firmware/applications/SignBuddy/FreeRTOSConfig.h, firmware/applications/SignBuddy/ble_uart.c, firmware/applications/SignBuddy/common.h, firmware/applications/SignBuddy/imu.c, firmware/applications/SignBuddy/main.c, firmware/applications/SignBuddy/sensors.c, firmware/applications/SignBuddy/task_config.h, firmware/applications/SignBuddy/tsc.c, firmware/applications/SignBuddy/tsc.h, firmware/libraries/system_time/system_time.c
Reverts adambujak/SignBuddy#82
=> Revert "changing tsc module to rtos scheme"

firmware/applications/SignBuddy/Makefile, firmware/applications/SignBuddy/adc.c, firmware/applications/SignBuddy/adc.h, firmware/applications/SignBuddy/dma.c, firmware/applications/SignBuddy/dma.h, firmware/applications/SignBuddy/flex.c, firmware/applications/SignBuddy/flex.h, firmware/applications/SignBuddy/main.c, firmware/applications/SignBuddy/nucleo_board.h, firmware/applications/SignBuddy/sensors.c, firmware/applications/SignBuddy/task_config.h
* Closes #71 
* Review after #94
=> Add flex sensor collection task

firmware/applications/SignBuddy/SignBuddy.pb.c, firmware/applications/SignBuddy/SignBuddy.pb.h, firmware/applications/SignBuddy/SignBuddy.proto
=> Add packet structure

firmware/applications/SignBuddy/flex.c, firmware/applications/SignBuddy/flex.h, firmware/applications/SignBuddy/sensors.c
=> Incorporate packet structure in sensors module

firmware/applications/SignBuddy/Makefile, firmware/applications/SignBuddy/ble_uart.c, firmware/applications/SignBuddy/ble_uart.h, firmware/applications/SignBuddy/comms.c, firmware/applications/SignBuddy/comms.h, firmware/applications/SignBuddy/crc.c, firmware/applications/SignBuddy/crc.h, firmware/applications/SignBuddy/dma.c, firmware/applications/SignBuddy/dma.h, firmware/applications/SignBuddy/flex.c, firmware/applications/SignBuddy/flex.h, firmware/applications/SignBuddy/main.c, firmware/applications/SignBuddy/nucleo_board.h, firmware/applications/SignBuddy/sensors.c, firmware/applications/SignBuddy/sensors.h, firmware/applications/SignBuddy/task_config.h, firmware/applications/SignBuddy/tsc.c
=> Add comms task

firmware/applications/SignBuddy/nucleo_board.h
conflict between touch sensor and imu pin fix
=> change imu pins

software/app/src/main/java/com/example/signbuddy/MainActivity.java
This logging is just temporary until I get protobuf set up
=> Change BLE name and log hex values

firmware/applications/SignBuddy/flex.c, firmware/applications/SignBuddy/tsc.c
There's a bit of variance in the thumb readings but it still works okay. I only calibrated with two references, hand closed and hand opened which I used as 90 and 0 degrees, and used 10 measurements from each, I added an excel sheet to the teams channel with the data
Closes #138
=> Flex sensor calibration
